# Site
name: Ярасту
title: Ярасту
description: Ярасту как стать выше ростом
logo: assets/images/logo.svg
favicon: assets/images/logo.svg
baseurl: /yarastu
google_analytics: G-N95K3D62RR
disqus: yarastu
mailchimp-list: "https://protonmail.us10.list-manage.com/subscribe?u=14aecd7ad2d0ab84409f294d7&id=cdaf122bc1"
include: ["_pages"]
youtube: "https://youtube.com/yarasty"
telegram: "https://t.me/yarasty"
podcast: "https://podcasts.apple.com/ru/podcast/%D1%8F-%D1%80%D0%B0%D1%81%D1%82%D1%83/id1526883743"
permalink: /:categories/:title
email: vadim@yarastu.ru

# Authors
authors:
  vadim:
    login: vadim
    name: Вадим Дмитриев
    display_name: Вадим
    avatar: vadim.jpg
    email: vadim@yarastu.ru
    web: "https://yarastu.ru"
    twitter: "https://twitter.com/yarasty8"
    description: Делюсь идеями, как вырасти ребенку, подростку, взрослому.

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Other
highlighter: none
markdown: kramdown
kramdown:
  auto_ids: false
  syntax_highlighter_opts:
      disable : true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Images
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      type: "posts"
    values:
      toc: false
      layout: post
      lang: ru
  - scope:
      type: "posts"
      path: "en"
    values:
      lang: en
  - scope:
      type: "pages"
    values:
      comments: false
      lang: ru
  - scope:
      type: "pages"
      path: "en"
    values:
      lang: en

exclude:
    - changelog.md
    - LICENSE.txt
    - README.md
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package-lock.json
    - package.json
    - assets/images/src
